= Lab4 - Creating Images Using Running Containers

Our containers are running from our previous module, but if we are required to stop one of them, all the applied changes will be lost. To retain their current state, we have to build images from them as follows:

[source,shell]
----
$ podman commit inventory_service inventory_image:manual
$ podman commit order_service order_image:manual
$ podman commit customer_service customer_image:manual
$ podman commit billing_service billing_image:manual
----

Note that we have added the `manual` tag to the container name only to identify that these images were created from containers made following the *manual process*.

Great! We have images with all the required files for each of our containers.

[source,shell]
----
$ podman images
REPOSITORY                         TAG         IMAGE ID      CREATED             SIZE
localhost/billing_image            manual      5a57576464cc  About a minute ago  480 MB
localhost/customer_image           manual      4984b299abcc  About a minute ago  479 MB
localhost/order_image              manual      1686fcc661b5  About a minute ago  480 MB
localhost/inventory_image          manual      c795e24d0157  About a minute ago  480 MB
----

Stop all the running containers

[source,shell]
----
$ podman stop -a
$ podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
----

and run them again but this time using the newly created images

[source,shell]
----
$ podman run --rm --name inventory_service --network host -d localhost/inventory_image:manual python3 inventory_service.py
$ podman run --rm --name order_service --network host -d localhost/order_image:manual python3 order_service.py
$ podman run --rm --name customer_service --network host -d localhost/customer_image:manual python3 customer_service.py
$ podman run --rm --name billing_service --network host -d localhost/billing_image:manual python3 billing_service.py
----

== Testing the application

// TODO: Add testing instructions

Note that when running the containers, we must use the image corresponding to the service in question. Instead of running `/bin/bash` as we did in the previous module, we directly run the application and don’t have to install anything else or copy files because they are already included in the image.
