=== Lab 11 - Securing our Application

Create a new login screen for our application

.authentication.py

Notice that the credentials are hardcoded.

If we want to test it locally, we can:

[source,shell]
----
$ python3 authentication.py
Enter your username: fakename
Enter your password: fakepassword
Error: Invalid username or password. Authentication failed.

$ python3 authentication.py
Enter your username: user123
Enter your password: password123
Welcome, user123! Authentication successful.
----

convert the solution into a container and test it.

.authContainerfile

Build, run and test!

[source,shell]
----
$ podman build -t authenticator:v1 .
$ podman run --rm -ti --name authenticator localhost/authenticator:v1
Enter your username: user123
Enter your password: password123
Welcome, user123! Authentication successful.
----

Passing all this information in clear text and every single time the container is executed is not the best approach

Modify our application to take the credentials from environment variables copy from solution/auth.py 

Build version 2, run and test!

[source,shell]
----
$ podman build -t authenticator:v2 .
$ podman run --rm -ti --name authenticator -e VALID_USERNAME=user123 -e VALID_PASSWORD=password123 localhost/authenticator:v2
Enter your username: user123
Enter your password: password123
Welcome, user123! Authentication successful.
----

Notice that this time, the code no longer has the credentials hardcoded; however, we are still passing them in clear text when running the container.

To avoid this, we can utilize secrets. Let’s add the secret directly using the following commands:

[source,shell]
----
$ printf "user123" | podman secret create username -
2fc833daa70b54c79f2dbce5c

$ printf "password123" | podman secret create password -
d7b9dff4f0d87bfb77401e2a4
----

Now we can list our secrets

[source,shell]
----
$ podman secret list
ID                         NAME        DRIVER      CREATED             UPDATED
2fc833daa70b54c79f2dbce5c  username    file        About a minute ago  About a minute ago
d7b9dff4f0d87bfb77401e2a4  password    file        About a minute ago  About a minute ago
----

Now we can rerun the container, registering the secrets as environment variables at runtime, and therefore, the real values are never exposed.

[source,shell]
----
$ podman run --rm -ti --name authenticator \
    --secret=username,type=env,target=VALID_USERNAME \
    --secret=password,type=env,target=VALID_PASSWORD \
    localhost/authenticator:v2
Enter your username: user123
Enter your password: password123
Welcome, user123! Authentication successful
----
