= Lab 10 - Troubleshooting the Application

Let’s review the logs of the application using the LNAV LogFile Navigator, which we will start by installing:

[source,shell]
----
$ sudo dnf install -y lnav
----

Use it against any of the running containers as follows:

[source,shell]
----
$ sudo journalctl CONTAINER_NAME=order_service | lnav
----

Monitor the performance of the application containers. The running processes can be seen with the following command:

[source,shell]
----
$ podman top order_service
----

Performance statistics can be found using the following command:

[source,shell]
----
$ podman stats
----

However, when using containers, we should always strive for self-healing processes. If you remember, in our previous modules, we continued to verify the availability of the application by testing it, like:

[source,shell]
----
$ ansible-playbook play.yml
----

What if we can add the health check at runtime?

[source,shell]
----
$ podman run --rm --name inventory_service --network pharmacy -p 5001:5001 \
    --health-cmd='curl http://0.0.0.0:5001/view_inventory || exit 1' \
    --health-interval=30s -d localhost/pharmacy:v5 inventory_service.py
----

Now we can run the health check at any time, and if there is no answer, it means we are OK!

After running the container with a health check, inspect its status with podman ps:

[source,shell]
----
$ podman ps
CONTAINER ID  IMAGE                  COMMAND              CREATED   STATUS            NAMES
c8d...        localhost/pharmacy:v5  inventory_service.py 15s ago   Up 14s (healthy)  inventory_service
----

Notice the status column includes the health of the container, such as (healthy). This gives you an immediate, at-a-glance view of your application's state.

[source,shell]
----
$ podman healthcheck run inventory_service
----

Even if we don’t run it manually, the health check is continuously being executed

[source,shell]
----
$ podman inspect --format='{{json .State.Health.Status}}' inventory_service
"healthy"
----
