= Lab 12 - Using Compose for the Pharmacy Application

We have advanced significantly in the creation of our application, but we are still handling it mostly in a manual manner. Every time we restart the application, we have to follow a specific process to do so, which is tedious and prone to error. To avoid this, let’s use Compose instead.

Ensure that you have either podman-compose or docker-compose in your environment.

Start by creating a new compose.yaml file:

We know we will need a volume

[source,yaml]
----
version: "4"

volumes:
  data:
----

We will require an isolated network:

[source,yaml]
----
networks:
  pharmacy:
    ipam:
      driver: default
----

Now add our services:

.compose.yaml
[source,yaml]
----
services:

  billing_service:
    image: localhost/pharmacy:v5
    restart: always
    deploy:
      replicas: 1
    ports:
      - "5004:5004"
    command: billing_service.py
    networks:
      - pharmacy
    detach: true

  customer_service:
    image: localhost/pharmacy:v5
    restart: always
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    command: customer_service.py
    networks:
      - pharmacy
    detach: true

  inventory_service:
    image: localhost/pharmacy:v5
    restart: always
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    command: inventory_service.py
    networks:
      - pharmacy
    detach: true

  order_service:
    image: localhost/pharmacy:v5
    restart: always
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    command: order_service.py
    networks:
      - pharmacy
    volumes:
      - data:/data
    detach: true
----

Bring our services up in detached mode using the following command:

[source,shell]
----
$ podman-compose up -d
----

And bring it down with the following command:

[source,shell]
----
$ podman-compose down
----

Notice that new networks, volumes, and containers were created, all prepended with the name of our project directory.

There is one more thing to consider. When versioning, we keep using tags like v1 or v2, but that will force us to constantly come back to the compose file whenever a new version is released, it's always a good idea to keep a copy of the latest version of everything tagged as latest so we don’t need to be specific on the version.

[source,shell]
----
$ podman tag localhost/pharmacy:v5 localhost/pharmacy:latest
----
